# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 026c41518cb101db7f3f6427fa0be663fe699113232f384d62d9a1701a8d15e3ea32fa0d7d791a96d71d0cc64e003a1ed0b3f9271e723af0855c818482e72fe1

test:
  secret_key_base: b791ce4f59adf2c0b578927d76b3f195b0631ba7987d72420b84b1e53846a44cdd056213652c922c9ea466c5739a35f0b524c4490eed7fef4a8ea4ccce2b685d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
